export const AUTH_TOKEN_NAME = 'authToken';
export const USER_ROLES = {
  VISITOR: 'VISITOR',
  EXHIBITOR: 'EXHIBITOR',
};

export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILED = 'USER_REGISTRATION_FAILED';

export const NETWORK_ISSUES = 'NETWORK_ISSUES';
